#server:
#  servlet:
#  #  定义项目的访问访问路径
#    context-path: /consumer
#    #定义端口号
#  port: 7001
spring:
  redis:
    cluster:
      #设置key的生存时间，当key过期时，它会被自动删除；
      expire-seconds: 120
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 5000
      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
      nodes: namenode22:6379,datanode23:6379,datanode24:6379,datanode25:6379,datanode26:6379,datanode27:6379
  application:
  #定义应用名称，即服务名称
    name: consumer-server
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

#数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 5Wy43g&mvI+u
    # 使用druid数据源
    #type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka/eureka
server:
  servlet:
    #  定义项目的访问访问路径
    context-path: /consumer
    #定义端口号
  port: 7001

#mybatis中mapper配置文件位置扫描
mybatis:
  mapper-locations: classpath:mapper/*.xml

name: name
